# Site settings
# =============

title: M. M. Bygrove
url: 'http://mmbygrove.com'
# description: “Writing fiction is like crossing the Atlantic Ocean in a bathtub.”

author:
  name: M. M. Bygrove
  email: mmbygrove@icloud.com
  # twitter_username: joshgerdes
  # facebook_username: joshgerdes
  # github_username:  joshgerdes
  # linkedin_username:  joshgerdes

# baseurl: /
# google_analytics: 'UA-XXXXXX-X'
disqus_shortname: 'mmbygrove'

defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
# ==============

# destination: _site
permalink: /:year/:title.html
paginate: 5
paginate_path: "/page:num"
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems:
  - jekyll-paginate

exclude:
  - README.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - jekyll
