# Site settings
# =============

title: M. M. Bygrove
url: 'http://mmbygrove.com'
# description: “Writing fiction is like crossing the Atlantic Ocean in a bathtub.”

author:
  name: M. M. Bygrove
  email: mmbygrove@icloud.com
  # twitter_username: joshgerdes
  # facebook_username: joshgerdes
  # github_username:  joshgerdes
  # linkedin_username:  joshgerdes

# baseurl: /
# google_analytics: 'UA-XXXXXX-X'
disqus_shortname: 'mmbygrove'

collections:
  flash:
    output: true

defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'
  - scope:
      path: ''
      type: 'flash'
    values:
      layout: 'flash'

# Build settings
# ==============

# destination: _site
permalink: /:year/:title.html
paginate: 1000
paginate_path: "/page:num"
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

exclude:
  - README.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - jekyll
