#!/usr/bin/env bash

VERSION='1.2.0'

# CONFIGURATION
# =============

# Default variables and their values
: ${RBENV_VARS_FILE:=".rbenv-vars"}
: ${JEKYLL_CLEAN:="jekyll clean"}
: ${JEKYLL_BUILD:="jekyll build"}
: ${JEKYLL_SERVE:="jekyll serve --open-url"}

# FUNCTIONS
# =========

# Document available command line options. This function
# simply outputs script's SYNOPSIS to the user terminal.
__help() {
cat << EOF
Usage:
    ${0} [options] [arguments]

    A custom wrapper to used to help with setting up and starting jekyll
    in the development environments.

        Options                 All options are optional and
        -------                 can be supplied in any order.

        -d --debug              Run jekyll in the debug mode (build, serve)
        -l --log=<path>         Redirect all output to a file
        -q --quiet              Suppress output of the script
        -? --help               Display this help message
        --version               Script and BASH version info

        Arguments               All agruments are optionals and
        ---------               can be supplied in any order.

        clean                   Removes all of jekyll build artefacts, bundled
                                gems, and version control files: Gemfile.lock,
                                .ruby-version.

        install                 Installs .ruby-version if the file is missing,
                                adds all required build tools (inc. ruby),
                                runs bundle install.

        upgrade                 Runs `brew upgrade`, followed by `clean` and
                                `install` targets.

        build                   Instructs jekyll to build your site and
                                populate the contents of the _site directory.

        serve, server           Instructs jekyll to build your site, then
                                starts the server and serves it locally.
                                (Default argument)

    <> - required parameters    [] - optional parameters
    Use 'less ${0}' to view further documentation.
EOF
}

# This function is executed after processing all supplied
# options but before looking at the script's arguments.
__init() {
    INIT_DIR="$pwd"
    cd $(dirname ${0})
    init_rbenv
}

# This function is called when the script receives an EXIT pseudo-signal. It
# simulates a common destructor behaviour inside BASH scripts. It allows this
# script to release and clean up resources upon termination.
__exit() {
    cd ${INIT_DIR}
}

# Insure the presence of OPTARG in the current scope. If OPTARG is missing then
# display help message via __help and exit with an error code.
require_OPTARG() {
    if [[ -z ${OPTARG} ]]; then
        echo "${0}: option requires an argument -- ${OPTKEY}" >&2
        __help
        exit 1
    fi
}

# Test if a given value means NO.
is_false() {
    local value="$(echo ${1} | tr [:upper:] [:lower:])"

    if [[ -z ${value} || ${value} =~ ^0|n|no|false|none|null|nil$ ]]; then
        return 0
    fi

    return 1
}

# Test if a given value means YES.
is_true() {
    if is_false ${1}; then
        return 1
    fi

    return 0
}

install_required_tools() {
    # test for curl
    if ! type -P curl >&-; then
        echo "Please install CURL before using this script"
        exit 1
    fi

    # test for homebrew
    if ! type -P brew >&-; then
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi

    # test for jq
    if ! type -P jq >&-; then
        brew install jq
    fi

    # test for fswatch
    if ! type -P fswatch >&-; then
        brew install fswatch
    fi

    # test for rbenv
    if ! type -P rbenv >&-; then
        brew install rbenv rbenv-vars
        init_rbenv
    fi

    # clean up the installation
    brew cleanup

    # check for installation errors
    if ! brew doctor; then
        exit 1;
    fi
}

# Initialise rbenv environments
init_rbenv() {
    if (type -P brew && type -P rbenv) >&-; then
        export RBENV_ROOT="$(brew --prefix)/var/rbenv"
        eval "$(rbenv init -)";
    fi
}

# COMMAND LINE OPTIONS
# =====================
#
# By default BASH does not provide support for long options. However, we can
# trick it into doing so by defining '-:' as part of the optspec. This
# exploits a non-standard behaviour of the shell which permits the
# option-argument to be concatenated to the option, eg: -f arg == -farg
while getopts "dl:q?-:" OPTKEY; do

    if [[ "${OPTKEY}" = '-' ]]; then
        OPTKEY=`echo ${OPTARG} | sed -e 's/=.*//'`
        OPTARG=`echo ${OPTARG} | sed -e "s/^${OPTKEY}=\{0,1\}//"`
    fi

    case ${OPTKEY} in
        'd'|'debug')
            JEKYLL_SERVE+=" --verbose --trace"
            JEKYLL_BUILD+=" --verbose --trace"
            ;;
        'l'|'log')
            require_OPTARG
            mkdir -p $(dirname ${OPTARG})
            exec 5>&1 6>&2 # Backup STDOUT and STDERR
            exec > ${OPTARG} 2>&1
            ;;
        'q'|'quiet')
            exec 5>&1 6>&2 # Backup STDOUT and STDERR
            exec >&-
            ;;
        'version')
            echo "Shell script $0 version ${VERSION}"
            echo `bash --version | head -n 1`
            exit
            ;;
        '?'|'help')
            __help
            exit
            ;;
        *)
            if [ "$OPTERR" = 1 ] && [ "${optspec:0:1}" != ":" ]; then
                echo "${0}: illegal option -- ${OPTKEY}" >&2
                __help
                exit 1
            fi
            ;;
    esac
done

# Clear all options and reset the command line argument count
shift $(( OPTIND -1 ))

# Check for an option-terminator string
if [[ "${1}" == "--" ]]; then
    shift
fi

# Initialise script destructor
trap __exit EXIT
__init

# SCRIPT ARGUMENTS
# ================

# Script is executed with no arguments
if [[ ${!#} == ${0} ]]; then
    ARGS='serve'
fi

# Upgrade brew resources
if [[ "${@}" = *'upgrade'* ]]; then
    ARGS= ${@//upgrade/clean install/}
    if ! brew upgrade --cleanup; then
        exit 1;
    fi
fi

# Process all supplied arguments
for ARG in ${ARGS-${@}}; do
    case ${ARG} in
        'clean')
            bundle exec ${JEKYLL_CLEAN}
            rm -Rf .bundle && echo "Removing $(pwd)/.bundle)"
            rm -fv Gemfile.lock && echo "Removing $(pwd)/Gemfile.lock)"
            rbenv local --unset
            ;;
        'install')
            install_required_tools
            if ! rbenv local >&-; then
                : ${GITHUB_PAGES_DEPENDENCIES:=$(curl -L "https://pages.github.com/versions.json")}
                : ${GITHUB_RUBY_VERSION:=$(echo ${GITHUB_PAGES_DEPENDENCIES} | jq -r '.ruby')}
            fi
            : ${GITHUB_RUBY_VERSION:=$(rbenv local)}
            : ${CURRENT_RUBY_VERSION:=$(ruby -e 'puts RUBY_VERSION')}
            if [[ -z "${GITHUB_RUBY_VERSION}" ]]; then
                echo "Failed to determine which version of ruby is required by github-pages."
                echo "Please visit https://pages.github.com/versions/, and install it manually."
            elif [[ "${GITHUB_RUBY_VERSION}" != "${CURRENT_RUBY_VERSION}" ]]; then
                rbenv install --skip-existing ${GITHUB_RUBY_VERSION} && \
                rbenv local ${GITHUB_RUBY_VERSION} && \
                ( gem update bundler || gem install bundler )
            fi
            if [[ ! -s "${RBENV_VARS_FILE}" ]]; then
                echo "Missing personal access token for github."
                echo "Please visit https://github.com/settings/tokens"
                echo "... and create a token with [repo -> public_repo] access rights"
                read -p "Personal access token: " JEKYLL_GITHUB_TOKEN
                echo "JEKYLL_GITHUB_TOKEN?=${JEKYLL_GITHUB_TOKEN}" > ${RBENV_VARS_FILE}
            fi
            git submodule update --recursive --remote
            bundle install --path .bundle
            ;;
        'build')
            bundle exec ${JEKYLL_BUILD}
            ;;
        'serve'|'server')
            bundle exec ${JEKYLL_SERVE} &
            JEKYLL_PID=$!
            sleep 2
            if ! ps $JEKYLL_PID >&-; then
                echo "Failed to start JEKYLL... Is it installed?"
                echo "Try running: ${0} install"
                exit 1
            fi
            JEKYLL_SERVE=${JEKYLL_SERVE//--open-url}
            trap 'JEKYLL_STOP=true' SIGINT
            while fswatch --one-event --timestamp ./_config.yml; do
                if is_true ${JEKYLL_STOP}; then
                    echo ""
                    break
                else
                    kill -TERM ${JEKYLL_PID} 2>&-
                    wait ${JEKYLL_PID} 2>&-
                    bundle exec ${JEKYLL_SERVE} &
                    JEKYLL_PID=$!
                fi
            done
            trap - SIGINT
            ;;
        *)
            # Fail if invalid command line argument is given
            echo "${0}: illegal argument -- ${ARG}" >&2
            __help
            exit 1
            ;;
    esac
done
